# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Player.create(name: 'Kevin', 
              championship_win_count: 1, 
              current_winner: false,
              nickname: "Gryyph",
              playoff_appearance_count: 2,
              playoff_win_count: 2,
              playoff_loss_count: 1,
              playoff_draw_count: 0,
              last_place_count: 0,
              years_in_league: 4,
              regular_win_count: 10,
              regular_draw_count: 0,
              regular_loss_count: 3)

Player.create(name: 'Danny', 
              championship_win_count: 0, 
              current_winner: false,
              nickname: "DLoSamuel",
              playoff_appearance_count: 0,
              playoff_win_count: 0,
              playoff_loss_count: 0,
              playoff_draw_count: 0,
              last_place_count: 0,
              years_in_league: 4,
              regular_win_count: 3,
              regular_draw_count: 0,
              regular_loss_count: 10)

Player.create(name: 'Bijan', 
              championship_win_count: 0, 
              current_winner: false,
              nickname: "bij",
              playoff_appearance_count: 1,
              playoff_win_count: 1,
              playoff_loss_count: 1,
              playoff_draw_count: 0,
              last_place_count: 0,
              years_in_league: 2,
              regular_win_count: 7,
              regular_draw_count: 0,
              regular_loss_count: 6)

Player.create(name: 'Forrest', 
              championship_win_count: 0, 
              current_winner: false,
              nickname: "GarbagePerson",
              playoff_appearance_count: 0,
              playoff_win_count: 0,
              playoff_loss_count: 0,
              playoff_draw_count: 0,
              last_place_count: 0,
              years_in_league: 4,
              regular_win_count: 3,
              regular_draw_count: 0,
              regular_loss_count: 10)

Player.create(name: 'Patrick', 
              championship_win_count: 0, 
              current_winner: false,
              nickname: "patograce",
              playoff_appearance_count: 1,
              playoff_win_count: 0,
              playoff_loss_count: 1,
              playoff_draw_count: 0,
              last_place_count: 0,
              years_in_league: 4,
              regular_win_count: 6,
              regular_draw_count: 0,
              regular_loss_count: 7)

Player.create(name: 'Nathan', 
              championship_win_count: 0, 
              current_winner: false,
              nickname: "Nathareth",
              playoff_appearance_count: 0,
              playoff_win_count: 0,
              playoff_loss_count: 0,
              playoff_draw_count: 0,
              last_place_count: 0,
              years_in_league: 4,
              regular_win_count: 5,
              regular_draw_count: 0,
              regular_loss_count: 8)

Player.create(name: 'Slava', 
              championship_win_count: 0, 
              current_winner: false,
              nickname: "The42069ers",
              playoff_appearance_count: 1,
              playoff_win_count: 2,
              playoff_loss_count: 1,
              playoff_draw_count: 0,
              last_place_count: 0,
              years_in_league: 2,
              regular_win_count: 8,
              regular_draw_count: 0,
              regular_loss_count: 5)

Player.create(name: 'Brandon', 
              championship_win_count: 1, 
              current_winner: true,
              nickname: "bmartyb",
              playoff_appearance_count: 1,
              playoff_win_count: 2,
              playoff_loss_count: 0,
              playoff_draw_count: 0,
              last_place_count: 0,
              years_in_league: 4,
              regular_win_count: 11,
              regular_draw_count: 0,
              regular_loss_count: 2)

Player.create(name: 'Parsa', 
              championship_win_count: 1, 
              current_winner: false,
              nickname: "parstoolsports",
              playoff_appearance_count: 1,
              playoff_win_count: 0,
              playoff_loss_count: 1,
              playoff_draw_count: 0,
              last_place_count: 0,
              years_in_league: 4,
              regular_win_count: 7,
              regular_draw_count: 0,
              regular_loss_count: 6)

Player.create(name: 'Sam', 
              championship_win_count: 1, 
              current_winner: false,
              nickname: "BadAtFF",
              playoff_appearance_count: 0,
              playoff_win_count: 0,
              playoff_loss_count: 0,
              playoff_draw_count: 0,
              last_place_count: 1,
              years_in_league: 4,
              regular_win_count: 5,
              regular_draw_count: 0,
              regular_loss_count: 8)